name: zts_go
services:
  postgres:
    image: postgres
    container_name: zts_go_postgres
    env_file:
      - path: ".env"
        required: true
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      zts_go:
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
  pgadmin:
    image: dpage/pgadmin4
    container_name: zts_go_pgadmin
    env_file:
      - path: ".env"
        required: true
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    networks:
      zts_go:
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  zts_go:
    driver: bridge

volumes:
  postgres:
  pgadmin: